---
# Application Configuration
app_name: devops-app
docker_image: sunflye/devops-info-service
docker_tag: latest
app_port: 5000
app_internal_port: 5000

# Docker Compose Configuration
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"

# Wipe Logic Control
web_app_wipe: false  # Default: do NOT wipe
restart_policy: unless-stopped

# Documentation:
# Set to true to remove application completely
# Wipe only:     ansible-playbook deploy.yml -e "web_app_wipe=true" --tags web_app_wipe
# Clean install: ansible-playbook deploy.yml -e "web_app_wipe=true"