apiVersion: v2
name: app-python
description: Helm chart for the DevOps course Python info service
type: application

# Chart version (SemVer) – increment when chart changes
version: 0.1.0

# Application version – matches your app version
appVersion: "1.0.0"