replicaCount: 1

image:
  # dev can use 'latest' for faster iteration
  tag: "latest"

service:
  type: NodePort
  nodePort: 30081

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 5