apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-python.fullname" . }}-preview
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "app-python.selectorLabels" . | nindent 4 }}
