apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: app-python
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-python
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: sunflye/devops-info-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DEMO_VAR
              value: "v2"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3