- name: restart app
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ docker_image }}:{{ docker_image_tag }}"
    state: started
    ports:
      - "{{ app_port }}:{{ app_internal_port }}"
    restart_policy: "{{ restart_policy }}"
    env:
      PORT: "{{ app_internal_port | string }}"
      HOST: "0.0.0.0"
    force_kill: yes