apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "app-python.fullname" . }}-post-install"
  labels:
    {{- include "app-python.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "app-python.fullname" . }}-post-install"
      labels:
        {{- include "app-python.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Post-install smoke test for {{ .Release.Name }}";
              sleep 5;
              echo "Post-install hook completed successfully"